services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "${SPRING_SERVER_PORT}:${SPRING_SERVER_PORT}"
    depends_on:
      - postgres
    environment:
      - SPRING_SERVER_PORT=${SPRING_SERVER_PORT}
      - SPRING_DATASOURCE_URL = ${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME = ${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD = ${SPRING_DATASOURCE_PASSWORD}